// tests/unit/core/playback_contract_compile_tests.cpp - header self-contained smoke
// Each cpp should include only one public header (generated by cmake).
// This is a minimal manual version.

#include "core/id/playback_id.h"
#include "core/time/playback_time.h"
#include "core/error/playback_error.h"
#include "core/state/playback_state.h"

int main(){ return 0; }
